---
# tasks file for roles/run_v2ray_bridge

- name: Run bridge node
  ansible.builtin.shell: docker-compose -f {{base_compose_path}}/v2ray_bridge_server/docker-compose.yml up -d

- name: Restart docker compose
  ansible.builtin.shell: docker-compose -f {{base_compose_path}}/v2ray_bridge_server/docker-compose.yml restart
