---
# tasks file for roles/run_v2ray_bridge

- name: Run bridge node
  ansible.builtin.shell: docker-compose -f {{ bridge_dockercompose_path }} up -d

- name: Restart docker compose
  ansible.builtin.shell: docker-compose -f {{ bridge_dockercompose_path }} restart
