---

- name: Config requirements
  gather_facts: yes
  hosts: all
  vars_files:
    - ./vars.yml  
  roles:
    - role: apt
      become: yes
    - role: hardening
      become: no
    - role: install_docker
      become: yes
    - role: clone
      become: no
    - role: config_v2ray
      become: no

- name: Config v2ray bridge
  gather_facts: yes
  hosts: v2ray_bridge
  vars_files:
    - ./vars.yml  
  roles:
    - run_v2ray_bridge

- name: Config v2ray upstream
  gather_facts: yes
  hosts: v2ray_upstream
  vars_files:
    - ./vars.yml  
  roles:
    - run_v2ray_upstream