---
# tasks file for roles/run_v2ray_upstream

- name: Run upstream node
  ansible.builtin.shell: docker-compose -f {{ upstream_dockercompose_path }} up -d

- name: Restart docker compose
  ansible.builtin.shell: docker-compose -f {{ upstream_dockercompose_path }} restart