---
# tasks file for roles/clone

- name: Unzip folder
  ansible.builtin.unarchive:
    src: "https://github.com/miladrahimi/v2ray-docker-compose/archive/refs/heads/master.zip"
    dest: "{{ ansible_env.HOME }}"
    remote_src: yes
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER  }}"