---
# tasks file for roles/clone

- name: Unzip folder
  ansible.builtin.unarchive:
    src: "https://github.com/miladrahimi/v2ray-docker-compose/archive/refs/heads/master.zip"
    remote_src: yes
    dest: "/home/{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user  }}"