---
# tasks file for roles/docker

- name: Install docker
  apt:
    name: docker
    state: latest
    update_cache: no

- name: Install docker compose plugin
  apt:
    name: docker-compose
    state: latest
    update_cache: no